### ISSUE TITLE
Bug report: duplicate title and description

### ISSUE THREAD

**Issue by pejhab** [learnweb/moodle-mod_moodleoverflow#121]
I have noticed the following problem on Moodle 4.1+ (Build: 20221209) and Overflow v4.1-r1 2022120600 when you reply to a discussion:

![image](https://user-images.githubusercontent.com/4097425/227715029-c300c6c6-a6b3-4813-997b-414ed8d71e5c.png)

**Comment by TamaroWalter** [comment]
Hi,

thank you for your bug report, we checked the problem and indeed, the forum title and description is rendered 2 times. The problem occured, because we integrated the the moodleoverflow header and added another header. We fixed the bug and additional header is removed, so that only the moodleoverflow header is being rendered.

Screenshot:
Before:
![duplicate issue3](https://user-images.githubusercontent.com/119226824/229460581-aeada31b-47df-4a7b-9378-72de27af8ad6.png)

After:
![duplicate issue4](https://user-images.githubusercontent.com/119226824/229460639-e646d497-e132-43ee-a3aa-05375f87ee69.png)


Regards,

Tamaro Walter
