### ISSUE TITLE
:view capability is unused

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-mod_moodleoverflow#24]
The plugin declares a moodleoverflow:view capability that is not used anywhere. It should either be used sensibly (cf. other plugins) or removed entirely.

Thanks, @Kathrin84, for noticing!

**Comment by Kathrin84** [comment]
Hi Jan,
in our production system we did set this capability to "not set" for all our roles.
This had the effect that nobody, except for the admin, could see the instance in the course anymore.
So this might be a magic capability, because it is not used anywhere in the code but it seem to be necessary, though.
So I think you can close this issue and you must not remove this capability from your plugin.
Best, Kathrin

**Comment by TamaraGunkel** [comment]
This capability is used by moodle core to check if a user is allowed to see the instance.
That's why the plugin does not check the capability itself.
