### ISSUE TITLE
Multiple selections of "helpful" and "solved"

### ISSUE THREAD

**Issue by rohkaemper** [learnweb/moodle-mod_moodleoverflow#44]
As of now, the role "teacher"  (and all other roles) can mark a single post as "helpful" and/or a single post as “solved”. Open questions that leave room for interpretation, a frequent occurence in, for example, the humanities, several answer can be helpful or solved. An adaption of the plugin is required to allow for multiple selections when marking posts.

**Comment by Dagefoerde** [comment]
Hi, thanks for the request. I believe a "solved" post in this scenario would be one that summarises, compares, and contrasts all answers in posts that could individually be considered "correct". However, I also believe that this kind of interaction is not to be expected. Therefore, this could be a good new feature.

We're putting this on our backlog. In the meantime, any help is appreciated. If you can propose a code solution, please feel free to create a pull request so that we can incorporate your code into our plugin.

**Comment by NinaHerrmann** [comment]
WIP in #123
