### ISSUE TITLE
Answers to subcomments are possible but not displayed

### ISSUE THREAD

**Issue by mputzi** [learnweb/moodle-mod_moodleoverflow#60]
If a topic in moodloverflow is answered, commented and then commented again, the last type of comment is sent via email but not displayed in moodle.
In moodleoverflow the counter for unread comments is correctly raised by an answer to a subcomment. But the link on the counter does not lead to the unread comment.

Either such a sub-sub-comment should be displayed or it should not be possible.

**Comment by justusdieckmann** [comment]
Hey,
I tested it with the newest Plugin-Release and Moodle 3.9, and there it worked as expected. (Image)
![image](https://user-images.githubusercontent.com/45795270/89088714-0de8b400-d39a-11ea-8f56-5ed3c61945da.png)

Like Stackoverflow, Moodleoverflow has only one "level" of comments on a answer. Because of that, commenting a comment on a answer is the same as commenting the answer itself.

I have to admit, that with the extra "Comment"-links for each comment, a user would probably expect to comment on that exact comment, and maybe we should consider changing something about that.

With that information: Did the newly added comment hide somewhere unexpected, or did it not show up at all in the discussion? :)

Greetings,
Justus

**Comment by mputzi** [comment]
Hi Justus,
We have moodle 3.9.1 and most recent version of the plugin. I tried to recreate the bug in moodleoverflow activities with different accounts and roles and – good news – it really can't be reproduced. So this issue should be **marked as resolved**.
But in our LMS there is still one moodleoverflow which displays 7 replies in the overview of topics for a certain topic and inside the topic only 5 replies are being displayed. I will continue trying to find out why this happened.
Kind regards,
Martin.

**Comment by mputzi** [comment]
Hi,
The activity the bug occurred in was initially not created with the current version of moodleoverflow. Moodleoverflow was upgraded later on. There were no PHP- or JS-errors in the logs or console. Although in the database all posts are present in table mdl_moodleoverflow_posts, some of them of a single user are not displayed in the topic view.
I double checked for missing HTML-tags or missing symbols in the tags of the posts, but the HTML of the posts was fine. The only thing is: there was no entry in mdl_moodleoverflow_discuss_subs for this discussion-id.
There were no anomalies in the other database tables of moodleoverflow.
The bug occurred only for posts of one single user with userid 311. The only thing special about this user is that the username contains the letter "ü". But since all strings are encoded utf8mb4 I can't imagine this being the problem. Other posts of this user were displayed as expected.
I deleted the faulty activity and recreated it. Next I will try to reproduce the bug with user 311 in the new activity.

**Comment by mputzi** [comment]
Hi again,
In a new moodleoverflow activity (moodle 3.9.1, plugin v3.9-r1 2020060500) with posts of the same users as before everything is displayed as expected.
Sorry for the false alarm.
Kind regards,
Martin.

**Comment by justusdieckmann** [comment]
Hi,
thanks for the update. If the bug somehow happens to you again, feel free to reopen the issue.

Greetings, 
Justus
