### ISSUE TITLE
Enhancements to Anonymous Mode

### ISSUE THREAD

**Issue by JaMeZ-B** [learnweb/moodle-mod_moodleoverflow#89]
(fellow WWU teacher here)

We are using the Overflow-Plug-in with great success in „Analysis I.“ and believe that part of the success is due to the fact, that people can ask questions anonymously. However the activity in that forum is so high, that the discussions become hard to follow if more than two people participate _due_ to the fact, that all users look the same. 

I suggest, that instead of „anonymous user“ it says „questioner“, „answerer 1“, „answerer 2“ and so on. That would make discussions much more easier to follow.
Adding some sort of „questioner“ label would also be helpful for the regular mode of the Overflow plug-in. With that in place one could simply number all participants of a question.

**Comment by justusdieckmann** [comment]
Hey @JaMeZ-B 

you're absolutely right, this was less than ideal. Both these points are now addressed, We also took the opportunity to change that the questioner is always anonymous in the comments, even when choosing the "question only"-anonymous mode. Thank you for the issue! It is also deployed in the Learnweb since Thursday :)

Justus

**Comment by JaMeZ-B** [comment]
Thank your for implementing this! -- it will definitely find its uses in the upcoming semester 👍 

Jannes
